# Generated by Django 3.0.2 on 2020-03-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QCC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(db_column='companyName', help_text='公司名', max_length=255, null=True)),
                ('shareholdername', models.CharField(blank=True, db_column='shareholdername', help_text='股东名称', max_length=255, null=True)),
                ('shareholderatio', models.CharField(blank=True, db_column='shareholdingratio', help_text='持股比例', max_length=255, null=True)),
                ('shareholdetype', models.CharField(blank=True, db_column='shareholdetype', help_text='股东类型', max_length=255, null=True)),
                ('subscription', models.CharField(blank=True, db_column='subscription', help_text='认缴出资额', max_length=255, null=True)),
                ('subscriptiondate', models.CharField(blank=True, db_column='subscriptiondate', help_text='认缴出资日期', max_length=255, null=True)),
            ],
            options={
                'db_table': 'shareholder',
                'managed': True,
            },
        ),
    ]
